// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7QRgkEu3mD5hxjQDZiUgERBi27dfgsQ',
    appId: '1:988857805289:web:03fdfe02f387d277b44378',
    messagingSenderId: '988857805289',
    projectId: 'wemanity-event-app',
    authDomain: 'wemanity-event-app.firebaseapp.com',
    storageBucket: 'wemanity-event-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccpE7NR1HJBz2X0Ngf8Ff-wL1Z50tVKk',
    appId: '1:988857805289:android:de4a3ad7ef5f7d4bb44378',
    messagingSenderId: '988857805289',
    projectId: 'wemanity-event-app',
    storageBucket: 'wemanity-event-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBocEQyAM-7V_sbV8tKUJvj9kNgo21_u5E',
    appId: '1:988857805289:ios:2804faac7abb375ab44378',
    messagingSenderId: '988857805289',
    projectId: 'wemanity-event-app',
    storageBucket: 'wemanity-event-app.appspot.com',
    iosClientId: '988857805289-ho7i4l2b01c9b962t897idvnvaqf0e35.apps.googleusercontent.com',
    iosBundleId: 'com.example.wemanity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBocEQyAM-7V_sbV8tKUJvj9kNgo21_u5E',
    appId: '1:988857805289:ios:a19e3ecac81a776bb44378',
    messagingSenderId: '988857805289',
    projectId: 'wemanity-event-app',
    storageBucket: 'wemanity-event-app.appspot.com',
    iosClientId: '988857805289-ikim56tpr35tise2lomprcf61o0rkl6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.wemanity.RunnerTests',
  );
}
